### ISSUE TITLE
[SUGGESTION] Custom model data for main gui things as arrow

### ISSUE THREAD

**Issue by Agaloth** [Ajneb97/PlayerKits#1]
As talked on spigot, it's about the back button, I know some people that needs the same features so I created that to make it easier and less spammy on spigot :)

**Comment by 10lulu** [comment]
Oh thx, i was about to make one as well. We rly need this feature

**Comment by Ajneb97** [comment]
I started uploading my plugins to github and making them open-source so you can add your own specific features ;)

**Comment by srbeastman** [comment]
This is such a good idea!!
