### ISSUE TITLE
Permissions bug

### ISSUE THREAD

**Issue by xcoolerboy** [Ajneb97/PlayerKits#36]
hello so i have issue with perms and when i set my lower rank to have

my rank1 have playerkits.kit.starter true

my rank2 have playerkits.kit.starter false

and when i set my admin rank that is parent from my rank2  playerkits.kit.* true he is not able to claim starter anymore or any other kits and i set false on rank2 can you fix this please

**Comment by Ajneb97** [comment]
playerkits.kit.* permission doesn't exists. You must add the permissions one by one.
