### ISSUE TITLE
Item is not correctly stored & preview item lores are lost

### ISSUE THREAD

**Issue by jeffry1829** [Ajneb97/PlayerKits#4]
Items with extra nbt tags given by other plugin will not be stored correctly(some nbt tags will disappear when claiming the kit)

When previewing items, item lores are gone.

I'm in minecraft version 1.17.1 with latest version plugin

Thank you!

**Comment by jeffry1829** [comment]
In plugin version 2.17.1, nbt tags are stored correctly
Only with the preview item lores problem

**Comment by Ajneb97** [comment]
What do you mean item lores are gone? The item in the preview inventory is the same as the one you receive in the kit, so it should the exact item with the lore included.

**Comment by jeffry1829** [comment]
> What do you mean item lores are gone? The item in the preview inventory is the same as the one you receive in the kit, so it should the exact item with the lore included.

In editing the kit items, there's no lores

**Comment by jeffry1829** [comment]
Also, I guess that you should use NBTBase.class in https://github.com/Ajneb97/PlayerKits/blob/main/src/pk/ajneb97/versiones/V1_17.java#L283
to avoid method not found exception.

Haven't see actual nms code though.

**Comment by jeffry1829** [comment]
I used 2.17.1's v1_17.class to 2.21.2
Seems like it works

**Comment by Ajneb97** [comment]
The nbt issue will be fixed in the next update, can you specify me the lore bug with pictures? Since I can't replicate the bug on my server.

**Comment by Ajneb97** [comment]
Ok I found the issue, I will fix it in the next update
